name: Deploy

on:
  release:
    types: [prereleased, released]

concurrency:
    group: cd-${{ github.ref }}
    cancel-in-progress: false

# env:
#     REPO_URL: ghcr.io
#     REPO_PROJECT: swiftdrivecorp
#     REPO_CONFIG: infra-deploy

# ghcr.io/swiftdrivecorp/frontend-admin-staging:123456
# ghcr.io/swiftdrivecorp/frontend-admin-prodution:123456

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: github
              run: echo "${{ toJSON(github) }}"
            - name: GITHUB_EVENT_NAME
              run: echo $GITHUB_EVENT_NAME

            # - id: extract
            #   name: Extract name
            #   run: echo "tf-workspace=$([[ $GITHUB_REF_NAME == 'main' ]] && echo 'qa2' || ( [[ $GITHUB_EVENT_NAME == 'release' ]] && ( [[ '${{ github.event.action }}' == 'prereleased' ]] && echo 'stage' || ( [[ '${{ github.event.action }}' == 'released' ]] && echo 'prod' || echo '' ) ) || echo '' ))" >> $GITHUB_OUTPUT
            # - name: Test extract name
            #   run: 'echo "Extracted environment name: $EXTRACTED"'
            #   env:
            #       EXTRACTED: ${{ steps.extract.outputs.tf-workspace }}



