name: Deploy

on:
  release:
    types: [prereleased, released]

concurrency:
    group: cd-${{ github.ref }}
    cancel-in-progress: false

# env:
#     REPO_URL: ghcr.io
#     REPO_PROJECT: swiftdrivecorp
#     REPO_CONFIG: infra-deploy

# ghcr.io/swiftdrivecorp/frontend-admin-staging:123456
# ghcr.io/swiftdrivecorp/frontend-admin-prodution:123456

jobs:
  test:
    name: "Extract environment name"
    runs-on: ubuntu-latest
    outputs:
      swf-environment: ${{ steps.extract.outputs.environment }}
    steps:
      - id: extract
        run: echo "swf-environment=$([[ '${{ github.event.action }}' == 'prereleased' ]] && echo 'staging' || echo 'production')" >> $GITHUB_OUTPUT
      - id: test
        run: 'echo "Extracted environment name: $EXTRACTED"'
        env:
          EXTRACTED: ${{ steps.extract.outputs.swf-environment }}



