name: CI

on:
  push:
    branches:
      - develop
      - releases/**
  pull_request:
    branches:
      - develop
      - features/**
      - bug/**
      - hotfix/**

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install commitlint
        run: |
          npm install @commitlint/cli@18
          npm install @commitlint/config-conventional@18

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Validate PR title with commitlint
        if: github.event_name == 'pull_request'
        uses: JulienKode/pull-request-name-linter-action@v0.5.0


